# Generated by Django 5.1.3 on 2024-12-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='author',
        ),
    ]
